<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeders.
     *
     * @return void
     */
    public function run()
    {
        DB::table('countries')->delete();
        
        DB::table('countries')->insert(
            [
                ['id'=>1, 'sortname'=>'AF', 'name'=>'Afghanistan','symbol'=>NULL, 'code'=>355, 'status'=>0],
                ['id'=>2, 'sortname'=>'AL', 'name'=>'Albania', 'symbol'=>NULL, 'code'=>355, 'status'=>0],
                ['id'=>3, 'sortname'=>'DZ', 'name'=>'Algeria', 'symbol'=>NULL, 'code'=>213, 'status'=>0],
                ['id'=>4,  'sortname'=>'AS', 'name'=>'American Samoa', 'symbol'=>NULL, 'code'=>1684, 'status'=>0],
                ['id'=>5, 'sortname'=>'AD', 'name'=>'Andorra', 'symbol'=>NULL, 'code'=>376, 'status'=>0],
                ['id'=>6, 'sortname'=>'AO', 'name'=>'Angola', 'symbol'=>NULL, 'code'=>244, 'status'=>0],
                ['id'=>7, 'sortname'=>'AI', 'name'=>'Anguilla', 'symbol'=>NULL, 'code'=>1264, 'status'=>0],
                ['id'=>8, 'sortname'=>'AQ', 'name'=>'Antarctica', 'symbol'=>NULL, 'code'=>0, 'status'=>0],
                ['id'=>9, 'sortname'=>'AG', 'name'=>'Antigua And Barbuda','symbol'=>NULL, 'code'=>1268, 0],
                ['id'=>10, 'sortname'=>'AR', 'name'=>'Argentina', 'symbol'=>NULL, 'code'=>54, 'status'=>0],
                ['id'=>11, 'sortname'=>'AM', 'name'=>'Armenia', 'symbol'=>NULL, 'code'=>374, 'status'=>0],
                ['id'=>12, 'sortname'=>'AW', 'name'=>'Aruba', 'symbol'=>'ƒ', 'code'=>297, 'status'=>0],
                ['id'=>13, 'sortname'=>'AU', 'name'=>'Australia', 'symbol'=>NULL, 'code'=>61, 'status'=>0],
                ['id'=>14, 'sortname'=>'AT', 'name'=>'Austria', 'symbol'=>NULL, 'code'=>43, 'status'=>0],
                ['id'=>15, 'sortname'=>'AZ', 'name'=>'Azerbaijan', 'symbol'=>'ман', 'code'=>994, 'status'=>0],
                ['id'=>16, 'sortname'=>'BS', 'name'=>'Bahamas The', 'symbol'=>NULL, 'code'=>1242, 'status'=>0],
                ['id'=>17, 'sortname'=>'BH', 'name'=>'Bahrain', 'symbol'=>NULL, 'code'=>973, 'status'=>0],
                ['id'=>18, 'sortname'=>'BD', 'name'=>'Bangladesh', 'symbol'=>NULL, 'code'=>880, 'status'=>0],
                ['id'=>19, 'sortname'=>'BB', 'name'=>'Barbados', 'symbol'=>NULL, 'code'=>1246, 'status'=>0],
                ['id'=>20, 'sortname'=>'BY', 'name'=>'Belarus', 'symbol'=>NULL, 'code'=>375, 'status'=>0],
                ['id'=>21, 'sortname'=>'BE', 'name'=>'Belgium', 'symbol'=>NULL, 'code'=>32, 'status'=>0],
                ['id'=>22, 'sortname'=>'BZ', 'name'=>'Belize', 'symbol'=>NULL, 'code'=>501, 'status'=>0],
                ['id'=>23, 'sortname'=>'BJ', 'name'=>'Benin', 'symbol'=>NULL, 'code'=>229, 'status'=>0],
                ['id'=>24, 'sortname'=>'BM', 'name'=>'Bermuda', 'symbol'=>NULL, 'code'=>1441, 'status'=>0],
                ['id'=>25, 'sortname'=>'BT', 'name'=>'Bhutan', 'symbol'=>NULL, 'code'=>975, 'status'=>0],
                ['id'=>26, 'sortname'=>'BO', 'name'=>'Bolivia', 'symbol'=>NULL, 'code'=>591, 'status'=>0],
                ['id'=>27, 'sortname'=>'BA', 'name'=>'Bosnia and Herzegovina', 'symbol'=>NULL, 'code'=>387, 'status'=>0],
                ['id'=>28, 'sortname'=>'BW', 'name'=>'Botswana', 'symbol'=>NULL, 'code'=>267, 'status'=>0],
                ['id'=>29, 'sortname'=>'BV', 'name'=>'Bouvet Island', 'symbol'=>NULL, 'code'=>0, 'status'=>0],
                ['id'=>30, 'sortname'=>'BR', 'name'=>'Brazil', 'symbol'=>NULL, 'code'=>55, 'status'=>0],
                ['id'=>31, 'sortname'=>'IO', 'name'=>'British Indian Ocean Territory', 'symbol'=>NULL, 'code'=>246, 'status'=>0],
                ['id'=>32, 'sortname'=>'BN', 'name'=>'Brunei', 'symbol'=>NULL, 'code'=>673, 'status'=>0],
                ['id'=>33, 'sortname'=>'BG', 'name'=>'Bulgaria', 'symbol'=>NULL, 'code'=>359, 'status'=>0],
                ['id'=>34, 'sortname'=>'BF', 'name'=>'Burkina Faso', 'symbol'=>NULL, 'code'=>226, 'status'=>0],
                ['id'=>35, 'sortname'=>'BI', 'name'=>'Burundi', 'symbol'=>NULL, 'code'=>257, 'status'=>0],
                ['id'=>36, 'sortname'=>'KH', 'name'=>'Cambodia', 'symbol'=>NULL, 'code'=>855, 'status'=>0],
                ['id'=>37, 'sortname'=>'CM', 'name'=>'Cameroon', 'symbol'=>NULL, 'code'=>237, 'status'=>0],
                ['id'=>38, 'sortname'=>'CA', 'name'=>'Canada', 'symbol'=>'$', 'code'=>1, 'status'=>1],
                ['id'=>39, 'sortname'=>'CV', 'name'=>'Cape Verde', 'symbol'=>NULL, 'code'=>238, 'status'=>0],
                ['id'=>40, 'sortname'=>'KY', 'name'=>'Cayman Islands', 'symbol'=>NULL, 'code'=>1345, 'status'=>0],
                ['id'=>41, 'sortname'=>'CF', 'name'=>'Central African Republic', 'symbol'=>NULL, 'code'=>236, 'status'=>0],
                ['id'=>42, 'sortname'=>'TD', 'name'=>'Chad', 'symbol'=>NULL, 'code'=>235, 'status'=>0],
                ['id'=>43, 'sortname'=>'CL', 'name'=>'Chile', 'symbol'=>NULL, 'code'=>56, 'status'=>0],
                ['id'=>44, 'sortname'=>'CN', 'name'=>'China', 'symbol'=>NULL, 'code'=>86, 'status'=>0],
                ['id'=>45, 'sortname'=>'CX', 'name'=>'Christmas Island', 'symbol'=>NULL, 'code'=>61, 'status'=>0],
                ['id'=>46, 'sortname'=>'CC', 'name'=>'Cocos [Keeling] Islands', 'symbol'=>NULL, 'code'=>672, 'status'=>0],
                ['id'=>47, 'sortname'=>'CO', 'name'=>'Colombia', 'symbol'=>NULL, 'code'=>57, 'status'=>0],
                ['id'=>48, 'sortname'=>'KM', 'name'=>'Comoros', 'symbol'=>NULL, 'code'=>269, 'status'=>0],
                ['id'=>49, 'sortname'=>'CG', 'name'=>'Republic Of The Congo', 'symbol'=>NULL, 'code'=>242, 'status'=>0],
                ['id'=>50, 'sortname'=>'CD', 'name'=>'Democratic Republic Of The Congo', 'symbol'=>NULL, 242, 'status'=>0],
                ['id'=>51, 'sortname'=>'CK', 'name'=>'Cook Islands', 'symbol'=>NULL, 'code'=>682, 'status'=>0],
                ['id'=>52, 'sortname'=>'CR', 'name'=>'Costa Rica', 'symbol'=>NULL, 'code'=>506, 'status'=>0],
                ['id'=>53, 'sortname'=>'CI', 'name'=>'Cote D\'Ivoire [Ivory Coast]', 'symbol'=>NULL, 'code'=>225, 'status'=>0],
                ['id'=>54, 'sortname'=>'HR', 'name'=>'Croatia [Hrvatska]', 'symbol'=>NULL, 'code'=>385, 'status'=>0],
                ['id'=>55, 'sortname'=>'CU', 'name'=>'Cuba', 'symbol'=>'₱', 'code'=>53, 'status'=>0],
                ['id'=>56, 'sortname'=>'CY', 'name'=>'Cyprus', 'symbol'=>'€', 'code'=>357, 'status'=>0],
                ['id'=>57, 'sortname'=>'CZ', 'name'=>'Czech Republic', 'symbol'=>'Kč', 'code'=>420, 'status'=>0],
                ['id'=>58, 'sortname'=>'DK', 'name'=>'Denmark', 'symbol'=>NULL, 'code'=>45,'status'=>0],
                ['id'=>59, 'sortname'=>'DJ', 'name'=>'Djibouti', 'symbol'=>NULL, 'code'=>253, 'status'=>0],
                ['id'=>60, 'sortname'=>'DM', 'name'=>'Dominica', 'symbol'=>NULL, 'code'=>1767, 'status'=>0],
                ['id'=>61, 'sortname'=>'DO', 'name'=>'Dominican Republic', 'symbol'=>NULL, 'code'=>1809, 'status'=>0],
                ['id'=>62, 'sortname'=>'TP', 'name'=>'East Timor', 'symbol'=>NULL, 'code'=>670, 'status'=>0],
                ['id'=>63, 'sortname'=>'EC', 'name'=>'Ecuador', 'symbol'=>NULL, 'code'=>593, 'status'=>0],
                ['id'=>64, 'sortname'=>'EG', 'name'=>'Egypt', 'symbol'=>NULL, 'code'=>20, 'status'=>0],
                ['id'=>65, 'sortname'=>'SV', 'name'=>'El Salvador', 'symbol'=>NULL, 'code'=>503, 'status'=>0],
                ['id'=>66, 'sortname'=>'GQ', 'name'=>'Equatorial Guinea', 'symbol'=>NULL, 'code'=>240, 'status'=>0],
                ['id'=>67, 'sortname'=>'ER', 'name'=>'Eritrea', 'symbol'=>NULL, 'code'=>291, 'status'=>0],
                ['id'=>68, 'sortname'=>'EE', 'name'=>'Estonia', 'symbol'=>NULL, 'code'=>372, 'status'=>0],
                ['id'=>69, 'sortname'=>'ET', 'name'=>'Ethiopia', 'symbol'=>NULL, 'code'=>251, 'status'=>0],
                ['id'=>70, 'sortname'=>'XA', 'name'=>'External Territories of Australia', 'symbol'=>NULL, 'code'=>61, 'status'=>0],
                ['id'=>71, 'sortname'=>'FK', 'name'=>'Falkland Islands', 'symbol'=>NULL, 'code'=>500, 'status'=>0],
                ['id'=>72, 'sortname'=>'FO', 'name'=>'Faroe Islands', 'symbol'=>NULL, 'code'=>298, 'status'=>0],
                ['id'=>73, 'sortname'=>'FJ', 'name'=>'Fiji Islands', 'symbol'=>NULL, 'code'=>679, 'status'=>0],
                ['id'=>74, 'sortname'=>'FI', 'name'=>'Finland', 'symbol'=>NULL, 'code'=>358, 'status'=>0],
                ['id'=>75, 'sortname'=>'FR', 'name'=>'France', 'symbol'=>NULL,'code'=> 33, 'status'=>0],
                ['id'=>76, 'sortname'=>'GF', 'name'=>'French Guiana', 'symbol'=>NULL, 'code'=>594, 'status'=>0],
                ['id'=>77, 'sortname'=>'PF', 'name'=>'French Polynesia', 'symbol'=>NULL, 'code'=>689, 'status'=>0],
                ['id'=>78, 'sortname'=>'TF', 'name'=>'French Southern Territories', 'symbol'=>NULL, 'code'=>0, 'status'=>0],
                ['id'=>79, 'sortname'=>'GA', 'name'=>'Gabon', 'symbol'=>NULL, 'code'=>241, 'status'=>0],
                ['id'=>80, 'sortname'=>'GM', 'name'=>'Gambia The', 'symbol'=>NULL, 'code'=>220, 'status'=>0],
                ['id'=>81, 'sortname'=>'GE', 'name'=>'Georgia','symbol'=>NULL, 'code'=>995, 'status'=>0],
                ['id'=>82, 'sortname'=>'DE', 'name'=>'Germany', 'symbol'=>NULL, 'code'=>49, 'status'=>0],
                ['id'=>83, 'sortname'=>'GH', 'name'=>'Ghana', 'symbol'=>'¢', 'code'=>233, 'status'=>1],
                ['id'=>84, 'sortname'=>'GI', 'name'=>'Gibraltar','symbol'=>NULL, 'code'=>350, 'status'=>0],
                ['id'=>85, 'sortname'=>'GR', 'name'=>'Greece', 'symbol'=>NULL, 'code'=>30, 'status'=>0],
                ['id'=>86, 'sortname'=>'GL', 'name'=>'Greenland', 'symbol'=>NULL, 'code'=>299, 'status'=>0],
                ['id'=>87, 'sortname'=>'GD', 'name'=>'Grenada','symbol'=> NULL, 'code'=>1473, 'status'=>0],
                ['id'=>88, 'sortname'=>'GP', 'name'=>'Guadeloupe', 'symbol'=>NULL, 'code'=>590, 'status'=>0],
                ['id'=>89, 'sortname'=>'GU', 'name'=>'Guam', 'symbol'=>NULL, 'code'=>1671, 'status'=>0],
                ['id'=>90, 'sortname'=>'GT', 'name'=>'Guatemala', 'symbol'=>NULL, 'code'=>502, 'status'=>0],
                ['id'=>91, 'sortname'=>'XU', 'name'=>'Guernsey and Alderney', 'symbol'=>NULL, 'code'=>44, 'status'=>0],
                ['id'=>92, 'sortname'=>'GN', 'name'=>'Guinea', 'symbol'=>NULL, 'code'=>224, 'status'=>0],
                ['id'=>93, 'sortname'=>'GW', 'name'=>'Guinea-Bissau', 'symbol'=>NULL, 'code'=>245, 'status'=>0],
                ['id'=>94, 'sortname'=>'GY', 'name'=>'Guyana', 'symbol'=>NULL, 'code'=>592, 'status'=>0],
                ['id'=>95, 'sortname'=>'HT', 'name'=>'Haiti', 'symbol'=>NULL, 'code'=>509, 'status'=>0],
                ['id'=>96, 'sortname'=>'HM', 'name'=>'Heard and McDonald Islands', 'symbol'=>NULL, 'code'=>0, 'status'=>0],
                ['id'=>97, 'sortname'=>'HN', 'name'=>'Honduras', 'symbol'=>NULL, 'code'=>504, 'status'=>0],
                ['id'=>98, 'sortname'=>'HK', 'name'=>'Hong Kong S.A.R.', 'symbol'=>NULL, 'code'=>852, 'status'=>0],
                ['id'=>99, 'sortname'=>'HU', 'name'=>'Hungary', 'symbol'=>NULL, 'code'=>36, 'status'=>0],
                ['id'=>100, 'sortname'=>'IS', 'name'=>'Iceland', 'symbol'=>NULL, 'code'=>354, 'status'=>0],
                ['id'=>101, 'sortname'=>'IN', 'name'=>'India', 'symbol'=>'₹', 'code'=>91, 'status'=>1],
                ['id'=>102, 'sortname'=>'ID', 'name'=>'Indonesia', 'symbol'=>NULL, 'code'=>62, 'status'=>0],
                ['id'=>103, 'sortname'=>'IR', 'name'=>'Iran', 'symbol'=>'﷼', 'code'=> '98', 'status'=>0],
                ['id'=>104, 'sortname'=>'IQ', 'name'=>'Iraq','symbol'=>NULL, 'code'=>964, 'status'=>0],
                ['id'=>105, 'sortname'=>'IE', 'name'=>'Ireland', 'symbol'=>NULL, 'code'=>353, 'status'=>0],
                ['id'=>106, 'sortname'=>'IL', 'name'=>'Israel', 'symbol'=>'₪', 'code'=>972, 'status'=>0],
                ['id'=>107, 'sortname'=>'IT', 'name'=>'Italy', 'symbol'=>NULL, 'code'=>39, 'status'=>0],
                ['id'=>108, 'sortname'=>'JM', 'name'=>'Jamaica', 'symbol'=>NULL, 'code'=>1876, 'status'=>0],
                ['id'=>109, 'sortname'=>'JP', 'name'=>'Japan', 'symbol'=>'¥', 'code'=>81, 'status'=>0],
                ['id'=>110, 'sortname'=>'XJ', 'name'=>'Jersey', 'symbol'=>NULL, 'code'=>44, 'status'=>0],
                ['id'=>111, 'sortname'=>'JO', 'name'=>'Jordan', 'symbol'=>NULL, 'code'=>962, 'status'=>0],
                ['id'=>112, 'sortname'=>'KZ', 'name'=>'Kazakhstan', 'symbol'=>'лв', 'code'=>7, 'status'=>0],
                ['id'=>113, 'sortname'=>'KE', 'name'=>'Kenya', 'symbol'=>NULL, 'code'=>254, 'status'=>0],
                ['id'=>114, 'sortname'=>'KI', 'name'=>'Kiribati', 'symbol'=>NULL, 'code'=>686, 'status'=>0],
                ['id'=>115, 'sortname'=>'KP', 'name'=>'Korea North', 'symbol'=>'₩', 'code'=>850,'status'=> 0],
                ['id'=>116, 'sortname'=>'KR', 'name'=>'Korea South', 'symbol'=>'₩', 'code'=>82, 'status'=>0],
                ['id'=>117, 'sortname'=>'KW', 'name'=>'Kuwait', 'symbol'=>NULL, 'code'=>965, 'status'=>0],
                ['id'=>118, 'sortname'=>'KG', 'name'=>'Kyrgyzstan', 'symbol'=>NULL, 'code'=>996, 'status'=>0],
                ['id'=>119, 'sortname'=>'LA', 'name'=>'Laos', 'symbol'=>'₭', 'code'=>856, 'status'=>0],
                ['id'=>120, 'sortname'=>'LV', 'name'=>'Latvia', 'symbol'=>NULL, 'code'=>371, 'status'=>0],
                ['id'=>121, 'sortname'=>'LB', 'name'=>'Lebanon', 'symbol'=>NULL, 'code'=>961, 'status'=>0],
                ['id'=>122, 'sortname'=>'LS', 'name'=>'Lesotho', 'symbol'=>NULL, 'code'=>266, 'status'=>0],
                ['id'=>123, 'sortname'=>'LR', 'name'=>'Liberia', 'symbol'=>NULL, 'code'=>231, 'status'=>0],
                ['id'=>124, 'sortname'=>'LY', 'name'=>'Libya', 'symbol'=>NULL, 'code'=>218, 'status'=>0],
                ['id'=>125, 'sortname'=>'LI', 'name'=>'Liechtenstein','symbol'=>NULL, 'code'=>423, 'status'=>0],
                ['id'=>126, 'sortname'=>'LT', 'name'=>'Lithuania', 'symbol'=>NULL, 'code'=>370, 'status'=>0],
                ['id'=>127, 'sortname'=>'LU', 'name'=>'Luxembourg', 'symbol'=>NULL, 'code'=>352, 'status'=>0],
                ['id'=>128, 'sortname'=>'MO', 'name'=>'Macau S.A.R.', 'symbol'=>NULL, 'code'=>853, 'status'=>0],
                ['id'=>129, 'sortname'=>'MK', 'name'=>'Macedonia', 'symbol'=>'ден', 'code'=>389, 'status'=>0],
                ['id'=>130, 'sortname'=>'MG', 'name'=>'Madagascar', 'symbol'=>NULL, 'code'=>261, 'status'=>0],
                ['id'=>131, 'sortname'=>'MW', 'name'=>'Malawi', 'symbol'=>NULL, 'code'=>265, 'status'=>0],
                ['id'=>132, 'sortname'=>'MY', 'name'=>'Malaysia', 'symbol'=>NULL, 'code'=>60,'status'=> 0],
                ['id'=>133, 'sortname'=>'MV', 'name'=>'Maldives', 'symbol'=>NULL, 'code'=>960, 'status'=>0],
                ['id'=>134, 'sortname'=>'ML', 'name'=>'Mali', 'symbol'=>NULL, 'code'=>223, 'status'=>0],
                ['id'=>135, 'sortname'=>'MT', 'name'=>'Malta', 'symbol'=>NULL, 'code'=>356, 'status'=>0],
                ['id'=>136, 'sortname'=>'XM', 'name'=>'Man [Isle of]', 'symbol'=>NULL, 'code'=>44, 'status'=>0],
                ['id'=>137, 'sortname'=>'MH', 'name'=>'Marshall Islands', 'symbol'=>NULL, 'code'=>692, 'status'=>0],
                ['id'=>138, 'sortname'=>'MQ', 'name'=>'Martinique','symbol'=> NULL, 'code'=>596, 'status'=>0],
                ['id'=>139, 'sortname'=>'MR', 'name'=>'Mauritania', 'symbol'=>NULL, 'code'=>222, 'status'=>0],
                ['id'=>140, 'sortname'=>'MU', 'name'=>'Mauritius','symbol'=> NULL, 'code'=>230, 'status'=>0],
                ['id'=>141, 'sortname'=>'YT', 'name'=>'Mayotte', 'symbol'=>NULL, 'code'=>269,'status'=> 0],
                ['id'=>142, 'sortname'=>'MX', 'name'=>'Mexico', 'symbol'=>NULL, 'code'=>52, 'status'=>0],
                ['id'=>143, 'sortname'=>'FM', 'name'=>'Micronesia', 'symbol'=>NULL,'code'=> 691, 'status'=>0],
                ['id'=>144, 'sortname'=>'MD', 'name'=>'Moldova','symbol'=> NULL, 'code'=>373, 'status'=>0],
                ['id'=>145, 'sortname'=>'MC', 'name'=>'Monaco', 'symbol'=>NULL, 'code'=>377, 'status'=>0],
                ['id'=>146, 'sortname'=>'MN', 'name'=>'Mongolia', 'symbol'=>'₮', 'code'=>976, 'status'=>0],
                ['id'=>147, 'sortname'=>'MS', 'name'=>'Montserrat', 'symbol'=>NULL, 'code'=>1664, 'status'=>0],
                ['id'=>148, 'sortname'=>'MA', 'name'=>'Morocco','symbol'=>NULL, 'code'=>212, 'status'=>0],
                ['id'=>149, 'sortname'=>'MZ', 'name'=>'Mozambique', 'symbol'=>NULL, 'code'=>258, 'status'=>0],
                ['id'=>150, 'sortname'=>'MM', 'name'=>'Myanmar', 'symbol'=>NULL, 'code'=>95, 'status'=>0],
                ['id'=>151, 'sortname'=>'NA', 'name'=>'Namibia', 'symbol'=>NULL, 'code'=>264, 'status'=>0],
                ['id'=>152, 'sortname'=>'NR', 'name'=>'Nauru', 'symbol'=>NULL, 'code'=>674, 'status'=>0],
                ['id'=>153, 'sortname'=>'NP', 'name'=>'Nepal', 'symbol'=>NULL, 'code'=>977, 'status'=>0],
                ['id'=>154, 'sortname'=>'AN', 'name'=>'Netherlands Antilles', 'symbol'=>NULL, 'code'=>599, 'status'=>0],
                ['id'=>155, 'sortname'=>'NL', 'name'=>'Netherlands The', 'symbol'=>NULL, 'code'=>31, 'status'=>0],
                ['id'=>156, 'sortname'=>'NC', 'name'=>'New Caledonia', 'symbol'=>NULL, 'code'=>687, 'status'=>0],
                ['id'=>157, 'sortname'=>'NZ', 'name'=>'New Zealand', 'symbol'=>NULL, 'code'=>64, 'status'=>0],
                ['id'=>158, 'sortname'=>'NI', 'name'=>'Nicaragua', 'symbol'=>NULL, 'code'=>505, 'status'=>0],
                ['id'=>159, 'sortname'=>'NE', 'name'=>'Niger', 'symbol'=>NULL, 'code'=>227, 'status'=>0],
                ['id'=>160, 'sortname'=>'NG', 'name'=>'Nigeria', 'symbol'=>'₦', 'code'=>234, 'status'=>1],
                ['id'=>161, 'sortname'=>'NU', 'name'=>'Niue', 'symbol'=>NULL, 'code'=>683, 'status'=>0],
                ['id'=>162, 'sortname'=>'NF', 'name'=>'Norfolk Island', 'symbol'=>NULL, 'code'=>672, 'status'=>0],
                ['id'=>163, 'sortname'=>'MP', 'name'=>'Northern Mariana Islands', 'symbol'=>NULL, 'code'=>1670, 'status'=>0],
                ['id'=>164, 'sortname'=>'NO', 'name'=>'Norway', 'symbol'=>NULL, 'code'=>47, 'status'=>0],
                ['id'=>165, 'sortname'=>'OM', 'name'=>'Oman', 'symbol'=>NULL, 'code'=>968, 'status'=>0],
                ['id'=>166, 'sortname'=>'PK', 'name'=>'Pakistan', 'symbol'=>'₨', 'code'=>92, 'status'=>0],
                ['id'=>167, 'sortname'=>'PW', 'name'=>'Palau', 'symbol'=>NULL, 'code'=>680, 'status'=>0],
                ['id'=>168, 'sortname'=>'PS', 'name'=>'Palestinian Territory Occupied', 'symbol'=>NULL, 'code'=>970, 'status'=>0],
                ['id'=>169, 'sortname'=>'PA', 'name'=>'Panama', 'symbol'=>NULL, 'code'=>507, 'status'=>0],
                ['id'=>170, 'sortname'=>'PG', 'name'=>'Papua new Guinea', 'symbol'=>NULL, 'code'=>675, 'status'=>0],
                ['id'=>171, 'sortname'=>'PY', 'name'=>'Paraguay', 'symbol'=>NULL, 'code'=>595, 'status'=>0],
                ['id'=>172, 'sortname'=>'PE', 'name'=>'Peru', 'symbol'=>NULL, 'code'=>51, 'status'=>0],
                ['id'=>173, 'sortname'=>'PH', 'name'=>'Philippines', 'symbol'=>NULL, 'code'=>63, 'status'=>0],
                ['id'=>174, 'sortname'=>'PN', 'name'=>'Pitcairn Island', 'symbol'=>NULL, 'code'=>0, 'status'=>0],
                ['id'=>175, 'sortname'=>'PL', 'name'=>'Poland', 'symbol'=>NULL, 'code'=>48, 'status'=>0],
                ['id'=>176, 'sortname'=>'PT', 'name'=>'Portugal', 'symbol'=>NULL, 'code'=>351, 'status'=>0],
                ['id'=>177, 'sortname'=>'PR', 'name'=>'Puerto Rico', 'symbol'=>NULL, 'code'=>1787, 'status'=>0],
                ['id'=>178, 'sortname'=>'QA', 'name'=>'Qatar', 'symbol'=>NULL, 'code'=>974, 'status'=>0],
                ['id'=>179, 'sortname'=>'RE', 'name'=>'Reunion', 'symbol'=>NULL, 'code'=>262, 'status'=>0],
                ['id'=>180, 'sortname'=>'RO', 'name'=>'Romania', 'symbol'=>NULL, 'code'=>40, 'status'=>0],
                ['id'=>181, 'sortname'=>'RU', 'name'=>'Russia', 'symbol'=>'руб',  'code'=>70, 'status'=>0],
                ['id'=>182, 'sortname'=>'RW', 'name'=>'Rwanda', 'symbol'=>NULL,  'code'=>250, 'status'=>0],
                ['id'=>183, 'sortname'=>'SH', 'name'=>'Saint Helena', 'symbol'=>NULL,  'code'=>290, 'status'=>0],
                ['id'=>184, 'sortname'=>'KN', 'name'=>'Saint Kitts And Nevis', 'symbol'=>NULL,  'code'=>1869, 'status'=>0],
                ['id'=>185, 'sortname'=>'LC', 'name'=>'Saint Lucia', 'symbol'=>NULL, 'code'=>1758,  'status'=>0],
                ['id'=>186, 'sortname'=>'PM', 'name'=>'Saint Pierre and Miquelon', 'symbol'=>NULL,  'code'=>508, 'status'=>0],
                ['id'=>187, 'sortname'=>'VC', 'name'=>'Saint Vincent And The Grenadines', 'symbol'=>NULL,  'code'=>1784, 'status'=>0],
                ['id'=>188, 'sortname'=>'WS', 'name'=>'Samoa', 'symbol'=>NULL,  'code'=>684, 'status'=>0],
                ['id'=>189, 'sortname'=>'SM', 'name'=>'San Marino', 'symbol'=>NULL,  'code'=>378, 'status'=>0],
                ['id'=>190, 'sortname'=>'ST', 'name'=>'Sao Tome and Principe', 'symbol'=>NULL,  'code'=>239, 'status'=>0],
                ['id'=>191, 'sortname'=>'SA', 'name'=>'Saudi Arabia', 'symbol'=>NULL,  'code'=>966, 'status'=>0],
                ['id'=>192, 'sortname'=>'SN', 'name'=>'Senegal', 'symbol'=>NULL,  'code'=>221, 'status'=>0],
                ['id'=>193, 'sortname'=>'RS', 'name'=>'Serbia', 'symbol'=>NULL,  'code'=>381, 'status'=>0],
                ['id'=>194, 'sortname'=>'SC', 'name'=>'Seychelles', 'symbol'=>NULL,  'code'=>248, 'status'=>0],
                ['id'=>195, 'sortname'=>'SL', 'name'=>'Sierra Leone', 'symbol'=>NULL,  'code'=>232,'status'=> 0],
                ['id'=>196, 'sortname'=>'SG', 'name'=>'Singapore', 'symbol'=>NULL,  'code'=>65, 'status'=>0],
                ['id'=>197, 'sortname'=>'SK', 'name'=>'Slovakia', 'symbol'=>NULL,  'code'=>421, 'status'=>0],
                ['id'=>198, 'sortname'=>'SI', 'name'=>'Slovenia', 'symbol'=>NULL,  'code'=>386, 'status'=>0],
                ['id'=>199, 'sortname'=>'XG', 'name'=>'Smaller Territories of the UK', 'symbol'=>NULL,  'code'=>44, 'status'=>0],
                ['id'=>200, 'sortname'=>'SB', 'name'=>'Solomon Islands', 'symbol'=>NULL,  'code'=>677, 'status'=>0],
                ['id'=>201, 'sortname'=>'SO', 'name'=>'Somalia', 'symbol'=>NULL,  'code'=>252, 'status'=>0],
                ['id'=>202, 'sortname'=>'ZA', 'name'=>'South Africa', 'symbol'=>NULL,  'code'=>27, 'status'=>0],
                ['id'=>203, 'sortname'=>'GS', 'name'=>'South Georgia', 'symbol'=>NULL,  'code'=>0, 'status'=>0],
                ['id'=>204, 'sortname'=>'SS', 'name'=>'South Sudan', 'symbol'=>NULL,  'code'=>211, 'status'=>0],
                ['id'=>205, 'sortname'=>'ES', 'name'=>'Spain', 'symbol'=>NULL,  'code'=>34, 'status'=>0],
                ['id'=>206, 'sortname'=>'LK', 'name'=>'Sri Lanka', 'symbol'=>NULL,  'code'=>94, 'status'=>0],
                ['id'=>207, 'sortname'=>'SD', 'name'=>'Sudan', 'symbol'=>NULL,  'code'=>249, 'status'=>0],
                ['id'=>208, 'sortname'=>'SR', 'name'=>'Suriname', 'symbol'=>NULL,  'code'=>597, 'status'=>0],
                ['id'=>209, 'sortname'=>'SJ', 'name'=>'Svalbard And Jan Mayen Islands', 'symbol'=>NULL,  'code'=>47, 'status'=>0],
                ['id'=>210, 'sortname'=>'SZ', 'name'=>'Swaziland', 'symbol'=>NULL,  'code'=>268, 'status'=>0],
                ['id'=>211, 'sortname'=>'SE',  'name'=>'Sweden', 'symbol'=>NULL,  'code'=>46, 'status'=>0],
                ['id'=>212, 'sortname'=>'CH',  'name'=>'Switzerland', 'symbol'=>NULL,  'code'=>41, 'status'=>0],
                ['id'=>213, 'sortname'=>'SY',  'name'=>'Syria', 'symbol'=>NULL,  'code'=>963, 'status'=>0],
                ['id'=>214, 'sortname'=>'TW',  'name'=>'Taiwan', 'symbol'=>NULL,  'code'=>886, 'status'=>0],
                ['id'=>215, 'sortname'=>'TJ', 'name'=>'Tajikistan', 'symbol'=>NULL,  'code'=>992, 'status'=>0],
                ['id'=>216, 'sortname'=>'TZ', 'name'=>'Tanzania', 'symbol'=>NULL,  'code'=>255, 'status'=>0],
                ['id'=>217, 'sortname'=>'TH', 'name'=>'Thailand', 'symbol'=>NULL,  'code'=>66, 'status'=>0],
                ['id'=>218, 'sortname'=>'TG', 'name'=>'Togo', 'symbol'=>NULL,  'code'=>228, 'status'=>0],
                ['id'=>219, 'sortname'=>'TK', 'name'=>'Tokelau','symbol'=> NULL,  'code'=>690, 'status'=>0],
                ['id'=>220, 'sortname'=>'TO', 'name'=>'Tonga', 'symbol'=>NULL,  'code'=>676, 'status'=>0],
                ['id'=>221, 'sortname'=>'TT', 'name'=>'Trinidad And Tobago', 'symbol'=>NULL,  'code'=>1868, 'status'=>0],
                ['id'=>222, 'sortname'=>'TN', 'name'=>'Tunisia','symbol'=> NULL,  'code'=>216, 'status'=>0],
                ['id'=>223, 'sortname'=>'TR', 'name'=>'Turkey', 'symbol'=>NULL,  'code'=>90, 'status'=>0],
                ['id'=>224, 'sortname'=>'TM', 'name'=>'Turkmenistan', 'symbol'=>NULL,  'code'=>7370, 'status'=>0],
                ['id'=>225, 'sortname'=>'TC', 'name'=>'Turks And Caicos Islands', 'symbol'=>NULL,  'code'=>1649, 'status'=>0],
                ['id'=>226, 'sortname'=>'TV', 'name'=>'Tuvalu', 'symbol'=>NULL,  'code'=>688, 'status'=>0],
                ['id'=>227, 'sortname'=>'UG', 'name'=>'Uganda', 'symbol'=>NULL,  'code'=>256, 'status'=>0],
                ['id'=>228, 'sortname'=>'UA', 'name'=>'Ukraine', 'symbol'=>NULL,  'code'=>380, 'status'=>0],
                ['id'=>229, 'sortname'=>'AE', 'name'=>'United Arab Emirates', 'symbol'=>NULL,  'code'=>971, 'status'=>0],
                ['id'=>230, 'sortname'=>'GB', 'name'=>'United Kingdom', 'symbol'=>'$',  'code'=>44, 'status'=>1],
                ['id'=>231, 'sortname'=>'US', 'name'=>'United States', 'symbol'=>'$',  'code'=>1, 'status'=>1],
                ['id'=>232, 'sortname'=>'UM', 'name'=>'United States Minor Outlying Islands', 'symbol'=>NULL,  'code'=>1, 'status'=>0],
                ['id'=>233, 'sortname'=>'UY', 'name'=>'Uruguay', 'symbol'=>NULL, 'code'=>598, 'status'=>0],
                ['id'=>234, 'sortname'=>'UZ', 'name'=>'Uzbekistan', 'symbol'=>NULL,  'code'=>998, 'status'=>0],
                ['id'=>235, 'sortname'=>'VU', 'name'=>'Vanuatu', 'symbol'=>NULL,  'code'=>678, 'status'=>0],
                ['id'=>236, 'sortname'=>'VA', 'name'=>'Vatican City State (Holy See)', 'symbol'=>NULL,  'code'=>39, 'status'=>0],
                ['id'=>237, 'sortname'=>'VE', 'name'=>'Venezuela', 'symbol'=>NULL,  'code'=>58, 'status'=>0],
                ['id'=>238, 'sortname'=>'VN', 'name'=>'Vietnam', 'symbol'=>'₫',  'code'=>84, 'status'=>0],
                ['id'=>239, 'sortname'=>'VG', 'name'=>'Virgin Islands (British)', 'symbol'=>NULL,  'code'=>1284, 'status'=>0],
                ['id'=>240, 'sortname'=>'VI', 'name'=>'Virgin Islands (US)', 'symbol'=>NULL,  'code'=>1340, 'status'=>0],
                ['id'=>241, 'sortname'=>'WF', 'name'=>'Wallis And Futuna Islands', 'symbol'=>NULL, 'code'=> 681, 'status'=>0],
                ['id'=>242, 'sortname'=>'EH', 'name'=>'Western Sahara', 'symbol'=>NULL,  'code'=>212, 'status'=>0],
                ['id'=>243, 'sortname'=>'YE', 'name'=>'Yemen', 'symbol'=>'﷼', 'code'=>967, 'status'=>0],
                ['id'=>244, 'sortname'=>'YU', 'name'=>'Yugoslavia', 'symbol'=>NULL,  'code'=>38, 'status'=>0],
                ['id'=>245, 'sortname'=>'ZM', 'name'=>'Zambia', 'symbol'=>NULL,  'code'=>260, 'status'=>0],
                ['id'=>246, 'sortname'=>'ZW', 'name'=>'Zimbabwe', 'symbol'=>NULL,  'code'=>263, 'status'=>0]
            ]
        );
    }
}