<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class LanguageSeeder extends Seeder
{
    /**
     * Run the database seeders.
     *
     * @return void
     */
    public function run()
    {
        DB::table('languages')->delete();
        
        DB::table('languages')->insert(
            [
                ['id'=>1, 'name'=>'Afar', 'key'=>'AA', 'sort_order'=>1, 'status'=>0],
			['id'=>2, 'name'=>'Abkhazian', 'key'=>'AB', 'sort_order'=>2, 'status'=>0],
			['id'=>3, 'name'=>'Afrikaans', 'key'=>'AF', 'sort_order'=>3, 'status'=>0],
			['id'=>4, 'name'=>'Akan', 'key'=>'AK', 'sort_order'=>4, 'status'=>0],
			['id'=>5, 'name'=>'Alemannic', 'key'=>'ALS', 'sort_order'=>5, 'status'=>0],
			['id'=>6, 'name'=>'Amharic', 'key'=>'AM', 'sort_order'=>6, 'status'=>0],
			['id'=>7, 'name'=>'Aragonese', 'key'=>'AN', 'sort_order'=>7, 'status'=>0],
			['id'=>8, 'name'=>'Angal', 'key'=>'ANG', 'sort_order'=>8, 'status'=>0],
			['id'=>9, 'name'=>'Anglo-Saxon / Old English', 'key'=>'ANG', 'sort_order'=>9, 'status'=>0],
			['id'=>10, 'name'=>'Arabic', 'key'=>'AR', 'sort_order'=>10, 'status'=>0],
			['id'=>11, 'name'=>'Aramaic', 'key'=>'ARC', 'sort_order'=>11, 'status'=>0],
			['id'=>12, 'name'=>'Assamese', 'key'=>'AS', 'sort_order'=>12, 'status'=>0],
			['id'=>13, 'name'=>'Asturian', 'key'=>'AST', 'sort_order'=>13, 'status'=>0],
			['id'=>14, 'name'=>'Avar', 'key'=>'AV', 'sort_order'=>14, 'status'=>0],
			['id'=>15, 'name'=>'Awadhi', 'key'=>'AWA', 'sort_order'=>15, 'status'=>0],
			['id'=>16, 'name'=>'Aymara', 'key'=>'AY', 'sort_order'=>16, 'status'=>0],
			['id'=>17, 'name'=>'Azerbaijani', 'key'=>'AZ', 'sort_order'=>17, 'status'=>0],
			['id'=>18, 'name'=>'Bashkir', 'key'=>'BAR', 'sort_order'=>2, 'status'=>0],
			['id'=>19, 'name'=>'Samogitian', 'key'=>'BAT-SMG', 'sort_order'=>19, 'status'=>0],
			['id'=>20, 'name'=>'Bikol', 'key'=>'BCL', 'sort_order'=>20, 'status'=>0],
			['id'=>21, 'name'=>'Belarusian', 'key'=>'BE', 'sort_order'=>21, 'status'=>0],
			['id'=>22, 'name'=>'Belarusian (Taraškievica)', 'key'=>'BE-X-OLD', 'sort_order'=>22, 'status'=>0],
			['id'=>23, 'name'=>'Bulgarian', 'key'=>'BG', 'sort_order'=>23, 'status'=>0],
			['id'=>24, 'name'=>'Bihari', 'key'=>'BH', 'sort_order'=>24, 'status'=>0],
			['id'=>25, 'name'=>'Bislama', 'key'=>'BI', 'sort_order'=>25, 'status'=>0],
			['id'=>26, 'name'=>'Bambara', 'key'=>'BM', 'sort_order'=>26, 'status'=>0],
			['id'=>27, 'name'=>'Bengali', 'key'=>'BN', 'sort_order'=>27, 'status'=>0],
			['id'=>28, 'name'=>'Tibetan', 'key'=>'BO', 'sort_order'=>28, 'status'=>0],
			['id'=>29, 'name'=>'Bishnupriya Manipuri', 'key'=>'BPY', 'sort_order'=>29, 'status'=>0],
			['id'=>30, 'name'=>'Breton', 'key'=>'BR', 'sort_order'=>30, 'status'=>0],
			['id'=>31, 'name'=>'Boro', 'key'=>'BRX', 'sort_order'=>31, 'status'=>0],
			['id'=>32, 'name'=>'Bosnian', 'key'=>'BS', 'sort_order'=>32, 'status'=>0],
			['id'=>33, 'name'=>'Buginese', 'key'=>'BUG', 'sort_order'=>33, 'status'=>0],
			['id'=>34, 'name'=>'Buriat (Russia)', 'key'=>'BXR', 'sort_order'=>34, 'status'=>0],
			['id'=>35, 'name'=>'Catalan', 'key'=>'CA', 'sort_order'=>35, 'status'=>0],
			['id'=>36, 'name'=>'Min Dong Chinese', 'key'=>'CDO', 'sort_order'=>36, 'status'=>0],
			['id'=>37, 'name'=>'Chechen', 'key'=>'CE', 'sort_order'=>37, 'status'=>0],
			['id'=>38, 'name'=>'Cebuano', 'key'=>'CEB', 'sort_order'=>38, 'status'=>0],
			['id'=>39, 'name'=>'Chamorro', 'key'=>'CH', 'sort_order'=>39, 'status'=>0],
			['id'=>40, 'name'=>'Choctaw', 'key'=>'CHO', 'sort_order'=>40, 'status'=>0],
			['id'=>41, 'name'=>'Cherokee', 'key'=>'CHR', 'sort_order'=>41, 'status'=>0],
			['id'=>42, 'name'=>'Cheyenne', 'key'=>'CHY', 'sort_order'=>42, 'status'=>0],
			['id'=>43, 'name'=>'Kurdish (Sorani)', 'key'=>'CKB', 'sort_order'=>43, 'status'=>0],
			['id'=>44, 'name'=>'Corsican', 'key'=>'CO', 'sort_order'=>44, 'status'=>0],
			['id'=>45, 'name'=>'Cree', 'key'=>'CR', 'sort_order'=>45, 'status'=>0],
			['id'=>46, 'name'=>'Czech', 'key'=>'CS', 'sort_order'=>46, 'status'=>0],
			['id'=>47, 'name'=>'Kashubian', 'key'=>'CSB', 'sort_order'=>47, 'status'=>0],
			['id'=>48, 'name'=>'Old Church Slavonic / Old Bulgarian', 'key'=>'CU', 'sort_order'=>48, 'status'=>0],
			['id'=>49, 'name'=>'Welsh', 'key'=>'CY', 'sort_order'=>49, 'status'=>0],
			['id'=>50, 'name'=>'Danish', 'key'=>'DA', 'sort_order'=>50, 'status'=>0],
			['id'=>51, 'name'=>'German', 'key'=>'DE', 'sort_order'=>51, 'status'=>0],
			['id'=>52, 'name'=>'Dimli', 'key'=>'DIQ', 'sort_order'=>52, 'status'=>0],
			['id'=>53, 'name'=>'Lower Sorbian', 'key'=>'DSB', 'sort_order'=>53, 'status'=>0],
			['id'=>54, 'name'=>'Divehi', 'key'=>'DV', 'sort_order'=>54, 'status'=>0],
			['id'=>55, 'name'=>'Dzongkha', 'key'=>'DZ', 'sort_order'=>55, 'status'=>0],
			['id'=>56, 'name'=>'Ewe', 'key'=>'EE', 'sort_order'=>56, 'status'=>0],
			['id'=>57, 'name'=>'Greek', 'key'=>'EL', 'sort_order'=>57, 'status'=>0],
			['id'=>58, 'name'=>'English', 'key'=>'EN', 'sort_order'=>58, 'status'=>0],
			['id'=>59, 'name'=>'Spanish', 'key'=>'ES', 'sort_order'=>59, 'status'=>0],
			['id'=>60, 'name'=>'Estonian', 'key'=>'ET', 'sort_order'=>60, 'status'=>0],
			['id'=>61, 'name'=>'Basque', 'key'=>'EU', 'sort_order'=>61, 'status'=>0],
			['id'=>62, 'name'=>'Extremaduran', 'key'=>'EXT', 'sort_order'=>62, 'status'=>0],
			['id'=>63, 'name'=>'Persian', 'key'=>'FA', 'sort_order'=>63, 'status'=>0],
			['id'=>64, 'name'=>'Peul', 'key'=>'FF', 'sort_order'=>64, 'status'=>0],
			['id'=>65, 'name'=>'Finnish', 'key'=>'FI', 'sort_order'=>65, 'status'=>0],
			['id'=>66, 'name'=>'Võro', 'key'=>'FIU-VRO', 'sort_order'=>66, 'status'=>0],
			['id'=>67, 'name'=>'Fijian', 'key'=>'FJ', 'sort_order'=>67, 'status'=>0],
			['id'=>68, 'name'=>'Faroese', 'key'=>'FO', 'sort_order'=>68, 'status'=>0],
			['id'=>69, 'name'=>'French', 'key'=>'FR', 'sort_order'=>69, 'status'=>0],
			['id'=>70, 'name'=>'Friulian', 'key'=>'FUR', 'sort_order'=>70, 'status'=>0],
			['id'=>71, 'name'=>'West Frisian', 'key'=>'FY', 'sort_order'=>71, 'status'=>0],
			['id'=>72, 'name'=>'Irish', 'key'=>'GA', 'sort_order'=>72, 'status'=>0],
			['id'=>73, 'name'=>'Gan Chinese', 'key'=>'GAN', 'sort_order'=>73, 'status'=>0],
			['id'=>74, 'name'=>'Garhwali', 'key'=>'GBM', 'sort_order'=>74, 'status'=>0],
			['id'=>75, 'name'=>'Scottish Gaelic', 'key'=>'GD', 'sort_order'=>75, 'status'=>0],
			['id'=>76, 'name'=>'Gilbertese', 'key'=>'GIL', 'sort_order'=>76, 'status'=>0],
			['id'=>77, 'name'=>'Galician', 'key'=>'GL', 'sort_order'=>77, 'status'=>0],
			['id'=>78, 'name'=>'Guarani', 'key'=>'GN', 'sort_order'=>78, 'status'=>0],
			['id'=>79, 'name'=>'Gothic', 'key'=>'GOT', 'sort_order'=>79, 'status'=>0],
			['id'=>80, 'name'=>'Gujarati', 'key'=>'GU', 'sort_order'=>80, 'status'=>0],
			['id'=>81, 'name'=>'Manx', 'key'=>'GV', 'sort_order'=>81, 'status'=>0],
			['id'=>82, 'name'=>'Hausa', 'key'=>'HN', 'sort_order'=>82, 'status'=>0],
			['id'=>83, 'name'=>'Hakka Chinese', 'key'=>'HAK', 'sort_order'=>83, 'status'=>0],
			['id'=>84, 'name'=>'Hawaiian', 'key'=>'HAW', 'sort_order'=>84, 'status'=>0],
			['id'=>85, 'name'=>'Hebrew', 'key'=>'GD', 'sort_order'=>85, 'status'=>0],
			['id'=>86, 'name'=>'Hindi', 'key'=>'HI', 'sort_order'=>86, 'status'=>0],
			['id'=>87, 'name'=>'Hiri Motu', 'key'=>'HO', 'sort_order'=>87, 'status'=>0],
			['id'=>88, 'name'=>'Croatian', 'key'=>'HR', 'sort_order'=>88, 'status'=>0],
			['id'=>89, 'name'=>'Haitian', 'key'=>'HT', 'sort_order'=>89, 'status'=>0],
			['id'=>90, 'name'=>'Hungarian', 'key'=>'HU', 'sort_order'=>90, 'status'=>0],
			['id'=>91, 'name'=>'Armenian', 'key'=>'HY', 'sort_order'=>91, 'status'=>0],
			['id'=>92, 'name'=>'Herero', 'key'=>'HZ', 'sort_order'=>92, 'status'=>0],
			['id'=>93, 'name'=>'Interlingua', 'key'=>'IA', 'sort_order'=>93, 'status'=>0],
			['id'=>94, 'name'=>'Indonesian', 'key'=>'ID', 'sort_order'=>94, 'status'=>0],
			['id'=>95, 'name'=>'Interlingue', 'key'=>'IE', 'sort_order'=>95, 'status'=>0],
			['id'=>96, 'name'=>'Igbo', 'key'=>'IG', 'sort_order'=>96, 'status'=>0],
			['id'=>97, 'name'=>'Sichuan Yi', 'key'=>'II', 'sort_order'=>97, 'status'=>0],
			['id'=>98, 'name'=>'Inupiak', 'key'=>'IK', 'sort_order'=>98, 'status'=>0],
			['id'=>99, 'name'=>'Ilokano', 'key'=>'ILO', 'sort_order'=>99, 'status'=>0],
			['id'=>100, 'name'=>'Ingush', 'key'=>'INH', 'sort_order'=>100, 'status'=>0],
			['id'=>101, 'name'=>'Ido', 'key'=>'IO', 'sort_order'=>101, 'status'=>0],
			['id'=>102, 'name'=>'Icelandic', 'key'=>'IS', 'sort_order'=>102, 'status'=>0],
			['id'=>103, 'name'=>'Italian', 'key'=>'IT', 'sort_order'=>103, 'status'=>0],
			['id'=>104, 'name'=>'Inuktitut', 'key'=>'IU', 'sort_order'=>104, 'status'=>0],
			['id'=>105, 'name'=>'Japanese', 'key'=>'JA', 'sort_order'=>105, 'status'=>0],
			['id'=>106, 'name'=>'Lojban', 'key'=>'JBO', 'sort_order'=>106, 'status'=>0],
			['id'=>107, 'name'=>'Javanese', 'key'=>'JV', 'sort_order'=>107, 'status'=>0],
			['id'=>108, 'name'=>'Georgian', 'key'=>'KA', 'sort_order'=>108, 'status'=>0],
			['id'=>109, 'name'=>'Kongo', 'key'=>'KG', 'sort_order'=>109, 'status'=>0],
			['id'=>110, 'name'=>'Kikuyu', 'key'=>'KI', 'sort_order'=>110, 'status'=>0],
			['id'=>111, 'name'=>'Kuanyama', 'key'=>'KJ', 'sort_order'=>111, 'status'=>0],
			['id'=>112, 'name'=>'Kazakh', 'key'=>'KK', 'sort_order'=>112, 'status'=>0],
			['id'=>113, 'name'=>'Greenlandic', 'key'=>'KL', 'sort_order'=>113, 'status'=>0],
			['id'=>114, 'name'=>'Cambodian', 'key'=>'KM', 'sort_order'=>114, 'status'=>0],
			['id'=>115, 'name'=>'Kannada', 'key'=>'KN', 'sort_order'=>115, 'status'=>0],
			['id'=>116, 'name'=>'Khowar', 'key'=>'KHW', 'sort_order'=>116, 'status'=>0],
			['id'=>117, 'name'=>'Korean', 'key'=>'KO', 'sort_order'=>117, 'status'=>0],
			['id'=>118, 'name'=>'Kanuri', 'key'=>'KR', 'sort_order'=>118, 'status'=>0],
			['id'=>119, 'name'=>'Kashmiri', 'key'=>'KS', 'sort_order'=>119, 'status'=>0],
			['id'=>120, 'name'=>'Ripuarian', 'key'=>'KSH', 'sort_order'=>120, 'status'=>0],
			['id'=>121, 'name'=>'Kurdish (Kurmanji)', 'key'=>'KU', 'sort_order'=>121, 'status'=>0],
			['id'=>122, 'name'=>'Kazakh', 'key'=>'KK', 'sort_order'=>122, 'status'=>0],
			['id'=>123, 'name'=>'Komi', 'key'=>'KV', 'sort_order'=>123, 'status'=>0],
			['id'=>124, 'name'=>'Cornish', 'key'=>'KW', 'sort_order'=>124, 'status'=>0],
			['id'=>125, 'name'=>'Kirghiz', 'key'=>'KY', 'sort_order'=>125, 'status'=>0],
			['id'=>126, 'name'=>'Latin', 'key'=>'LA', 'sort_order'=>126, 'status'=>0],
			['id'=>127, 'name'=>'Ladino / Judeo-Spanish', 'key'=>'LAD', 'sort_order'=>127, 'status'=>0],
			['id'=>128, 'name'=>'Lango', 'key'=>'LAN', 'sort_order'=>128, 'status'=>0],
			['id'=>129, 'name'=>'Luxembourgish', 'key'=>'LB', 'sort_order'=>129, 'status'=>0],
			['id'=>130, 'name'=>'Ganda', 'key'=>'LG', 'sort_order'=>130, 'status'=>0],
			['id'=>131, 'name'=>'Limburgian', 'key'=>'LI', 'sort_order'=>131, 'status'=>0],
			['id'=>132, 'name'=>'Ligurian', 'key'=>'LIJ', 'sort_order'=>132, 'status'=>0],
			['id'=>133, 'name'=>'Lombard', 'key'=>'LMO', 'sort_order'=>133, 'status'=>0],
			['id'=>134, 'name'=>'Lingala', 'key'=>'LN', 'sort_order'=>134, 'status'=>0],
			['id'=>135, 'name'=>'Laotian', 'key'=>'LO', 'sort_order'=>135, 'status'=>0],
			['id'=>136, 'name'=>'Laz', 'key'=>'LZZ', 'sort_order'=>136, 'status'=>0],
			['id'=>137, 'name'=>'Lithuanian', 'key'=>'LT', 'sort_order'=>137, 'status'=>0],
			['id'=>138, 'name'=>'Latvian', 'key'=>'LV', 'sort_order'=>138, 'status'=>0],
			['id'=>139, 'name'=>'Banyumasan', 'key'=>'MAP-BMS', 'sort_order'=>139, 'status'=>0],
			['id'=>140, 'name'=>'Malagasy', 'key'=>'MG', 'sort_order'=>140, 'status'=>0],
			['id'=>141, 'name'=>'Mandarin', 'key'=>'MAN', 'sort_order'=>141, 'status'=>0],
			['id'=>142, 'name'=>'Marshallese', 'key'=>'MH', 'sort_order'=>142, 'status'=>0],
			['id'=>143, 'name'=>'Māori', 'key'=>'MI', 'sort_order'=>143, 'status'=>0],
			['id'=>144, 'name'=>'Minangkabau', 'key'=>'MIN', 'sort_order'=>144, 'status'=>0],
			['id'=>145, 'name'=>'Macedonian', 'key'=>'MK', 'sort_order'=>145, 'status'=>0],
			['id'=>146, 'name'=>'Malayalam', 'key'=>'ML', 'sort_order'=>146, 'status'=>0],
			['id'=>147, 'name'=>'Mongolian / Judeo-Spanish', 'key'=>'MN', 'sort_order'=>147, 'status'=>0],
			['id'=>148, 'name'=>'Moldovan', 'key'=>'MO', 'sort_order'=>148, 'status'=>0],
			['id'=>149, 'name'=>'Marathi', 'key'=>'MR', 'sort_order'=>149, 'status'=>0],
			['id'=>150, 'name'=>'Mara', 'key'=>'MRH', 'sort_order'=>150, 'status'=>0],
			['id'=>151, 'name'=>'Malay', 'key'=>'MS', 'sort_order'=>151, 'status'=>0],
			['id'=>152, 'name'=>'Maltese', 'key'=>'MT', 'sort_order'=>152, 'status'=>0],
			['id'=>153, 'name'=>'Creek / Muskogee', 'key'=>'MUS', 'sort_order'=>153, 'status'=>0],
			['id'=>154, 'name'=>'Mirandese', 'key'=>'MWL', 'sort_order'=>154, 'status'=>0],
			['id'=>155, 'name'=>'Burmese', 'key'=>'MY', 'sort_order'=>155, 'status'=>0],
			['id'=>156, 'name'=>'Nauruan', 'key'=>'NA', 'sort_order'=>156, 'status'=>0],
			['id'=>157, 'name'=>'Nahuatl', 'key'=>'NAH', 'sort_order'=>157, 'status'=>0],
			['id'=>158, 'name'=>'Neapolitan', 'key'=>'NAP', 'sort_order'=>158, 'status'=>0],
			['id'=>159, 'name'=>'North Ndebele', 'key'=>'ND', 'sort_order'=>159, 'status'=>0],
			['id'=>160, 'name'=>'Low German / Low Saxon', 'key'=>'NDS', 'sort_order'=>160, 'status'=>0],
			['id'=>161, 'name'=>'Dutch Low Saxon', 'key'=>'NDS-NL', 'sort_order'=>161, 'status'=>0],
			['id'=>162, 'name'=>'Nepali', 'key'=>'NE', 'sort_order'=>162, 'status'=>0],
			['id'=>163, 'name'=>'Newar', 'key'=>'NEW', 'sort_order'=>163, 'status'=>0],
			['id'=>164, 'name'=>'Ndonga', 'key'=>'Dutch', 'sort_order'=>164, 'status'=>0],
			['id'=>165, 'name'=>'Norwegian Nynorsk', 'key'=>'NN', 'sort_order'=>165, 'status'=>0],
			['id'=>166, 'name'=>'South Ndebele', 'key'=>'NR', 'sort_order'=>166, 'status'=>0],
			['id'=>167, 'name'=>'Northern Sotho', 'key'=>'NSO', 'sort_order'=>167, 'status'=>0],
			['id'=>168, 'name'=>'Norman', 'key'=>'NRM', 'sort_order'=>168, 'status'=>0],
			['id'=>169, 'name'=>'Navajo', 'key'=>'NV', 'sort_order'=>169, 'status'=>0],
			['id'=>170, 'name'=>'Chichewa', 'key'=>'NY', 'sort_order'=>170, 'status'=>0],
			['id'=>171, 'name'=>'Occitan', 'key'=>'OC', 'sort_order'=>171, 'status'=>0],
			['id'=>172, 'name'=>'Ojibwa', 'key'=>'OJ', 'sort_order'=>172, 'status'=>0],
			['id'=>173, 'name'=>'Oromo', 'key'=>'OM', 'sort_order'=>173, 'status'=>0],
			['id'=>174, 'name'=>'Oriya', 'key'=>'OR', 'sort_order'=>174, 'status'=>0],
			['id'=>175, 'name'=>'Ossetian / Ossetic', 'key'=>'OS', 'sort_order'=>175, 'status'=>0],
			['id'=>176, 'name'=>'Panjabi / Punjabi', 'key'=>'PA', 'sort_order'=>176, 'status'=>0],
			['id'=>177, 'name'=>'Pangasinan', 'key'=>'PAG', 'sort_order'=>177, 'status'=>0],
			['id'=>178, 'name'=>'Kapampangan', 'key'=>'PAM', 'sort_order'=>178, 'status'=>0],
			['id'=>179, 'name'=>'Papiamentu', 'key'=>'PAP', 'sort_order'=>179, 'status'=>0],
			['id'=>180, 'name'=>'Pennsylvania German', 'key'=>'PDC', 'sort_order'=>180, 'status'=>0],
			['id'=>181, 'name'=>'Pali', 'key'=>'PI', 'sort_order'=>181, 'status'=>0],
			['id'=>182, 'name'=>'Norfolk', 'key'=>'PIH', 'sort_order'=>182, 'status'=>0],
			['id'=>183, 'name'=>'Polish', 'key'=>'PL', 'sort_order'=>183, 'status'=>0],
			['id'=>184, 'name'=>'Piedmontese', 'key'=>'PMS', 'sort_order'=>184, 'status'=>0],
			['id'=>185, 'name'=>'Pashto', 'key'=>'PS', 'sort_order'=>185, 'status'=>0],
			['id'=>186, 'name'=>'Portuguese', 'key'=>'PT', 'sort_order'=>186, 'status'=>0],
			['id'=>187, 'name'=>'Quechua', 'key'=>'QU', 'sort_order'=>187, 'status'=>0],
			['id'=>188, 'name'=>'Raeto Romance', 'key'=>'RM', 'sort_order'=>188, 'status'=>0],
			['id'=>189, 'name'=>'Romani', 'key'=>'RMY', 'sort_order'=>189, 'status'=>0],
			['id'=>190, 'name'=>'Kirundi', 'key'=>'RN', 'sort_order'=>190, 'status'=>0],
			['id'=>191, 'name'=>'Romanian', 'key'=>'RO', 'sort_order'=>191, 'status'=>0],
			['id'=>192, 'name'=>'Aromanian', 'key'=>'ROA-RUP', 'sort_order'=>192, 'status'=>0],
			['id'=>193, 'name'=>'Russian', 'key'=>'RU', 'sort_order'=>193, 'status'=>0],
			['id'=>194, 'name'=>'Rwandi', 'key'=>'RW', 'sort_order'=>194, 'status'=>0],
			['id'=>195, 'name'=>'Sanskrit', 'key'=>'SA', 'sort_order'=>195, 'status'=>0],
			['id'=>196, 'name'=>'Sardinian', 'key'=>'SC', 'sort_order'=>196, 'status'=>0],
			['id'=>197, 'name'=>'Sicilian', 'key'=>'SCN', 'sort_order'=>197, 'status'=>0],
			['id'=>198, 'name'=>'Scots', 'key'=>'SCO', 'sort_order'=>198, 'status'=>0],
			['id'=>199, 'name'=>'Sindhi', 'key'=>'SD', 'sort_order'=>199, 'status'=>0],
			['id'=>200, 'name'=>'Northern Sami', 'key'=>'NY', 'sort_order'=>200, 'status'=>0],
			['id'=>201, 'name'=>'Sango', 'key'=>'SG', 'sort_order'=>201, 'status'=>0],
			['id'=>202, 'name'=>'Serbo-Croatian', 'key'=>'SH', 'sort_order'=>202, 'status'=>0],
			['id'=>203, 'name'=>'Sinhalese', 'key'=>'SI', 'sort_order'=>203, 'status'=>0],
			['id'=>204, 'name'=>'Simple English', 'key'=>'SIMPLE', 'sort_order'=>204, 'status'=>0],
			['id'=>205, 'name'=>'Slovak', 'key'=>'SK', 'sort_order'=>205, 'status'=>0],
			['id'=>206, 'name'=>'Slovenian', 'key'=>'SL', 'sort_order'=>206, 'status'=>0],
			['id'=>207, 'name'=>'Samoan', 'key'=>'SM', 'sort_order'=>207, 'status'=>0],
			['id'=>208, 'name'=>'Shona', 'key'=>'SN', 'sort_order'=>208, 'status'=>0],
			['id'=>209, 'name'=>'Somalia', 'key'=>'SO', 'sort_order'=>209, 'status'=>0],
			['id'=>300, 'name'=>'Albanian', 'key'=>'SQ', 'sort_order'=>300, 'status'=>0],
			['id'=>301, 'name'=>'Serbian', 'key'=>'SR', 'sort_order'=>301, 'status'=>0],
			['id'=>302, 'name'=>'Swati', 'key'=>'SS', 'sort_order'=>302, 'status'=>0],
			['id'=>303, 'name'=>'Southern Sotho', 'key'=>'ST', 'sort_order'=>303, 'status'=>0],
			['id'=>304, 'name'=>'Sundanese', 'key'=>'SU', 'sort_order'=>304, 'status'=>0],
			['id'=>305, 'name'=>'Swedish', 'key'=>'SV', 'sort_order'=>305, 'status'=>0],
			['id'=>306, 'name'=>'Swahili', 'key'=>'SW', 'sort_order'=>306, 'status'=>0],
			['id'=>307, 'name'=>'Tamil', 'key'=>'TA', 'sort_order'=>307, 'status'=>0],
			['id'=>308, 'name'=>'Telugu', 'key'=>'TE', 'sort_order'=>308, 'status'=>0],
			['id'=>309, 'name'=>'Tetum', 'key'=>'TET', 'sort_order'=>309, 'status'=>0],
			['id'=>310, 'name'=>'Tajik', 'key'=>'TG', 'sort_order'=>310, 'status'=>0],
			['id'=>311, 'name'=>'Thai', 'key'=>'TH', 'sort_order'=>311, 'status'=>0],
			['id'=>312, 'name'=>'Tigrinya', 'key'=>'TI', 'sort_order'=>312, 'status'=>0],
			['id'=>313, 'name'=>'Turkmen', 'key'=>'TK', 'sort_order'=>313, 'status'=>0],
			['id'=>314, 'name'=>'Tagalog', 'key'=>'TL', 'sort_order'=>314, 'status'=>0],
			['id'=>315, 'name'=>'Klingon', 'key'=>'TLH', 'sort_order'=>315, 'status'=>0],
			['id'=>316, 'name'=>'Tswana', 'key'=>'TN', 'sort_order'=>316, 'status'=>0],
			['id'=>317, 'name'=>'Tonga', 'key'=>'TO', 'sort_order'=>317, 'status'=>0],
			['id'=>318, 'name'=>'Tok Pisin', 'key'=>'TPI', 'sort_order'=>318, 'status'=>0],
			['id'=>319, 'name'=>'Turkish', 'key'=>'TR', 'sort_order'=>319, 'status'=>0],
			['id'=>320, 'name'=>'Tsonga', 'key'=>'TS', 'sort_order'=>320, 'status'=>0],
			['id'=>321, 'name'=>'Tatar', 'key'=>'TT', 'sort_order'=>321, 'status'=>0],
			['id'=>322, 'name'=>'Tumbuka', 'key'=>'TUM', 'sort_order'=>322, 'status'=>0],
			['id'=>323, 'name'=>'Twi', 'key'=>'TW', 'sort_order'=>323, 'status'=>0],
			['id'=>324, 'name'=>'Tahitian', 'key'=>'TY', 'sort_order'=>324, 'status'=>0],
			['id'=>325, 'name'=>'Udmurt', 'key'=>'UDM', 'sort_order'=>325, 'status'=>0],
			['id'=>326, 'name'=>'Uyghur', 'key'=>'UG', 'sort_order'=>326, 'status'=>0],
			['id'=>327, 'name'=>'Ukrainian', 'key'=>'UK', 'sort_order'=>327, 'status'=>0],
			['id'=>328, 'name'=>'Urdu', 'key'=>'UR', 'sort_order'=>328, 'status'=>0],
			['id'=>329, 'name'=>'Uzbek', 'key'=>'UZ', 'sort_order'=>329, 'status'=>0],
			['id'=>330, 'name'=>'Uzbeki Afghanistan', 'key'=>'UZ_AF', 'sort_order'=>330, 'status'=>0],
			['id'=>331, 'name'=>'Venda', 'key'=>'VE', 'sort_order'=>331, 'status'=>0],
			['id'=>332, 'name'=>'Vietnamese', 'key'=>'VI', 'sort_order'=>332, 'status'=>0],
			['id'=>333, 'name'=>'Venetian', 'key'=>'VEC', 'sort_order'=>333, 'status'=>0],
			['id'=>334, 'name'=>'West Flemish', 'key'=>'VLS', 'sort_order'=>334, 'status'=>0],
			['id'=>335, 'name'=>'Volapük', 'key'=>'VO', 'sort_order'=>335, 'status'=>0],
			['id'=>336, 'name'=>'Walloon', 'key'=>'WA', 'sort_order'=>336, 'status'=>0],
			['id'=>337, 'name'=>'Waray / Samar-Leyte Visayan', 'key'=>'WAR', 'sort_order'=>337, 'status'=>0],
			['id'=>338, 'name'=>'Wolof', 'key'=>'WO', 'sort_order'=>338, 'status'=>0],
			['id'=>339, 'name'=>'Kalmyk', 'key'=>'XAL', 'sort_order'=>339, 'status'=>0],
			['id'=>340, 'name'=>'Xhosa', 'key'=>'XH', 'sort_order'=>340, 'status'=>0],
			['id'=>341, 'name'=>'Megrelian', 'key'=>'XMF', 'sort_order'=>341, 'status'=>0],
			['id'=>342, 'name'=>'Yiddish', 'key'=>'YI', 'sort_order'=>342, 'status'=>0],
			['id'=>343, 'name'=>'Yoruba', 'key'=>'YO', 'sort_order'=>343, 'status'=>0],
			['id'=>344, 'name'=>'Zhuang', 'key'=>'ZA', 'sort_order'=>344, 'status'=>0],
			['id'=>345, 'name'=>'Chinese', 'key'=>'ZH', 'sort_order'=>345, 'status'=>0],
			['id'=>346, 'name'=>'Classical Chinese', 'key'=>'ZH-CLASSICAL', 'sort_order'=>346, 'status'=>0],
			['id'=>347, 'name'=>'Minnan', 'key'=>'ZH-MIN-NAN', 'sort_order'=>347, 'status'=>0],
			['id'=>348, 'name'=>'Cantonese', 'key'=>'ZH-YUE', 'sort_order'=>348, 'status'=>0],
			['id'=>349, 'name'=>'Zulu', 'key'=>'ZU', 'sort_order'=>349, 'status'=>0]
            ]
        );
    }
}