<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CreateCustomersTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('customers', function (Blueprint $table) {
            $table->id();
            $table->string('name')->comment('customer name');
            $table->string('email')->comment('customer email address');
            $table->integer('country_id')->comment('reference as a country table')->nullable();
            $table->string('mobile_number')->comment('customer mobile number');
            $table->integer('reference_id')->comment('reference as a old customer')->default(0);
            $table->string('refer_code')->comment('unique reference code')->default(0);
            $table->string('password')->comment('customer access hash password');
            $table->string('csrf_code')->comment('customer password code')->default(0);
            $table->integer('csrf_pin')->comment('customer password pin')->default(0);
            $table->tinyInteger('gender')->comment('0: Other, 1: Male, 2: Fe-Male')->default(0);
            $table->date('dob')->comment('customer birthdate')->default(NULL);
            $table->string('address')->comment('customer address')->default(null);
            $table->string('pincode')->comment('customer local code')->default(null);
            $table->string('device_id')->comment('customer device id')->default(null);
            $table->string('profile_pic')->comment('customer profile picture')->default(null);
            $table->string('notification_token')->comment('customer mobile notification access token')->nullable();
            $table->tinyInteger('isRegister')->comment('0: Email, 1: Mobile, 2: Facebook Login, 3: Apple Login')->default(0);
            $table->string('facebook_token')->comment('Generated by facebook access token')->nullable();
            $table->string('apple_token')->comment('Generated by apple access token')->nullable();
            $table->tinyInteger('status')->comment('0: Disabled, 1: Enabled')->default('0');
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('customers');
    }
}
